export const countryCodes = [
    { code: "+93", name: "Afghanistan", flag: "🇦🇫" },
    { code: "+355", name: "Albania", flag: "🇦🇱" },
    { code: "+213", name: "Algeria", flag: "🇩🇿" },
    { code: "+376", name: "Andorra", flag: "🇦🇩" },
    { code: "+244", name: "Angola", flag: "🇦🇴" },
    { code: "+54", name: "Argentina", flag: "🇦🇷" },
    { code: "+61", name: "Australia", flag: "🇦🇺" },
    { code: "+43", name: "Austria", flag: "🇦🇹" },
    { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
    { code: "+32", name: "Belgium", flag: "🇧🇪" },
    { code: "+55", name: "Brazil", flag: "🇧🇷" },
    { code: "+359", name: "Bulgaria", flag: "🇧🇬" },
    { code: "+1-", name: "Canada", flag: "🇨🇦" },
    { code: "+86", name: "China", flag: "🇨🇳" },
    { code: "+57", name: "Colombia", flag: "🇨🇴" },
    { code: "+385", name: "Croatia", flag: "🇭🇷" },
    { code: "+357", name: "Cyprus", flag: "🇨🇾" },
    { code: "+420", name: "Czech Republic", flag: "🇨🇿" },
    { code: "+45", name: "Denmark", flag: "🇩🇰" },
    { code: "+20", name: "Egypt", flag: "🇪🇬" },
    { code: "+358", name: "Finland", flag: "🇫🇮" },
    { code: "+33", name: "France", flag: "🇫🇷" },
    { code: "+49", name: "Germany", flag: "🇩🇪" },
    { code: "+30", name: "Greece", flag: "🇬🇷" },
    { code: "+91", name: "India", flag: "🇮🇳" },
    { code: "+62", name: "Indonesia", flag: "🇮🇩" },
    { code: "+353", name: "Ireland", flag: "🇮🇪" },
    { code: "+972", name: "Israel", flag: "🇮🇱" },
    { code: "+39", name: "Italy", flag: "🇮🇹" },
    { code: "+81", name: "Japan", flag: "🇯🇵" },
    { code: "+82", name: "South Korea", flag: "🇰🇷" },
    { code: "+371", name: "Latvia", flag: "🇱🇻" },
    { code: "+370", name: "Lithuania", flag: "🇱🇹" },
    { code: "+60", name: "Malaysia", flag: "🇲🇾" },
    { code: "+52", name: "Mexico", flag: "🇲🇽" },
    { code: "+31", name: "Netherlands", flag: "🇳🇱" },
    { code: "+64", name: "New Zealand", flag: "🇳🇿" },
    { code: "+47", name: "Norway", flag: "🇳🇴" },
    { code: "+92", name: "Pakistan", flag: "🇵🇰" },
    { code: "+51", name: "Peru", flag: "🇵🇪" },
    { code: "+63", name: "Philippines", flag: "🇵🇭" },
    { code: "+48", name: "Poland", flag: "🇵🇱" },
    { code: "+351", name: "Portugal", flag: "🇵🇹" },
    { code: "+40", name: "Romania", flag: "🇷🇴" },
    { code: "+7", name: "Russia", flag: "🇷🇺" },
    { code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "+65", name: "Singapore", flag: "🇸🇬" },
    { code: "+421", name: "Slovakia", flag: "🇸🇰" },
    { code: "+386", name: "Slovenia", flag: "🇸🇮" },
    { code: "+27", name: "South Africa", flag: "🇿🇦" },
    { code: "+34", name: "Spain", flag: "🇪🇸" },
    { code: "+46", name: "Sweden", flag: "🇸🇪" },
    { code: "+41", name: "Switzerland", flag: "🇨🇭" },
    { code: "+90", name: "Turkey", flag: "🇹🇷" },
    { code: "+44", name: "United Kingdom", flag: "🇬🇧" },
    { code: "+1", name: "United States", flag: "🇺🇸" },
    { code: "+998", name: "Uzbekistan", flag: "🇺🇿" },
    { code: "+84", name: "Vietnam", flag: "🇻🇳" }
];
